### ISSUE TITLE
Responsive profile page

### ISSUE THREAD

**Issue by vinsdragonis** [vinsdragonis/Project-Nexus#102]
In a recent update, the profile page had an enhancement that makes it more attractive than the previous version. However, the page is not fully responsive since the components weren't _completely modified_ to work on **mobile devices**, leaving a few edge cases uncovered.

While most of the components seem to work as expected up to a certain extent, the panel showing the **username, email, and date of joining**, in particular, seems to be cluttered in _mobile view_ and needs fixing.

**Comment by vikashjajra** [comment]
I have registered from the register page but when I log in, it shows _**something went wrong**_!

**Comment by vikashjajra** [comment]
I've created a PR with a fix for this issue.

**Comment by vinsdragonis** [comment]
The issue seems to persist for some reason. Could you please post a working screenshot of this in mobile view?

**Comment by vinsdragonis** [comment]
Could you change those 3 componentsfrom inline to block? I think that should solve the problem.

**Comment by Sam-Takahashi** [comment]
Can you provide a screenshot of the problematic area? I'll take a look.

**Comment by vinsdragonis** [comment]
![Screenshot_20220825-023559_Chrome.jpg](https://user-images.githubusercontent.com/37930821/186523478-582e542a-3170-4313-ba60-5044ee94b4ef.jpg)

**Comment by vikashjajra** [comment]
![Screenshot from 2022-08-25 10-25-35](https://user-images.githubusercontent.com/96776232/186578397-d3840867-0a21-46af-9cbf-269d31e748a8.png)

**Comment by vinsdragonis** [comment]
Not sure if that's device-specific, but I couldn't get that responsiveness on my devices. Can you try to make them block-styled rather than inline? I assume that should fix the issue.

**Comment by Sam-Takahashi** [comment]
Can you tell me the name of the device you're viewing the app with?

**Comment by Sam-Takahashi** [comment]
It's probably a breakpoint issue.
Can you tell me the name of the device you're viewing the app with?

**Comment by vinsdragonis** [comment]
I'm using a Samsung Galaxy S20 Ultra.

**Comment by vikashjajra** [comment]
> It's probably a breakpoint issue. Can you tell me the name of the device you're viewing the app with?

The breakpoint is the same as the Hamburger one.

**Comment by vinsdragonis** [comment]
I think this has been taken care of as part of another pull request @Sam-Takahashi recently opened. So we can close this issue considering it is resolved for now.
