### ISSUE TITLE
Change categories input textbox to take multiple values

### ISSUE THREAD

**Issue by vinsdragonis** [vinsdragonis/Project-Nexus#105]
Right now, the input textbox for specifying a post's categories seems to take only one value and adds it to an array. This is not the expected way to store a post's categories.
Users should be able to add multiple categories to a single post and that should be pushed into the array. The categories document should dynamically add any new values.

**Comment by mridulKapur** [comment]
I can work on this.
We can basically take the input as comma separated string from the user and create the array from it.

**Comment by vinsdragonis** [comment]
Sure, go right ahead!

**Comment by mridulKapur** [comment]
#106 created pull request.

**Comment by mridulKapur** [comment]
Opened a PR fixing the issue.
