### ISSUE TITLE
Endless homepage loading

### ISSUE THREAD

**Issue by vinsdragonis** [vinsdragonis/Project-Nexus#115]
**Describe the bug**
The front page seems to endlessly show the loading animation but doesn't show the posts loaded from the database.

**Expected behavior**
After retrieving the posts from the database, the loading animation should stop, and the homepage must render them.

**Comment by vikashjajra** [comment]
Can't reproduce the issue. Please provide steps to recreate or post a screenshot of the browser console errors if there are any.

**Comment by vinsdragonis** [comment]
Hey! This has now been fixed, there was a huge latency in loading of posts, but now it works fine
