### ISSUE TITLE
Guest users can't see individual posts

### ISSUE THREAD

**Issue by vikashjajra** [vinsdragonis/Project-Nexus#123]
**Describe the bug**
When no user is logged in and a post link is clicked, the post contents won't load properly.

**To Reproduce**
1. Go to [projectnexus.netlify.app](https://projectnexus.netlify.app)
2. Log out if already logged in
3. Open any post
4. See error in browser console

**Expected behavior**
When a guest user opens a post, the post should open as usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/96776232/189276493-105282ed-fe4f-4bae-984c-84fc89b9ef7b.png)

**Desktop (please complete the following information):**
 - OS: Linux / Ubuntu
 - Browser: Chrome
 - Version: 105.0.5195.102

**Additional context**
The frontend probably checks for user id to decide whether to enable update mode or not, but since no user is logged in, user id doesn't exist.

**Comment by vinsdragonis** [comment]
This has been observed during a recent update. We initially decided to ignore it assuming it was an uncommon occurrence, but since it seems to persist, it needs a fix soon. Would you like to take this up?

**Comment by vikashjajra** [comment]
Sure! I did work on a solution for this on my local copy. I'll make a PR.

**Comment by vikashjajra** [comment]
#126 fixes this issue
