### ISSUE TITLE
Show password button on login form

### ISSUE THREAD

**Issue by vikashjajra** [vinsdragonis/Project-Nexus#124]
**Is your feature request related to a problem? Please describe.**
During the testing, I was required to log out and log back in to see if redirection was working properly. I mistyped the password and couldn't log in to my account. After retyping my whole password a couple of times, I managed to type it correctly. But this made me realize, that the project can really use a show password feature on the login page.

**Describe the solution you'd like**
There should be a show password button on the page that shows the password you've typed and you can see if there's a mistype. Additionally, the button could work as a toggler to show and hide passwords.

**Additional context**
The password input field uses the type password which masks the contents of it and shows black dots instead. The toggle button can change the type of the field to text and to the password again to show and hide the password respectively.

**Comment by vinsdragonis** [comment]
This is an essential feature, yes. Would you like to take it @vikashjajra?

**Comment by vikashjajra** [comment]
I'd be happy to unless there's is someone just learning basics who can learn a thing or two.

**Comment by vikashjajra** [comment]
#126 fixes this issue.
