### ISSUE TITLE
Enhance User Experience: Display Error Messages as Popups or Toast Notifications

### ISSUE THREAD

**Issue by swati082001** [vinsdragonis/Project-Nexus#506]
Currently, error messages during registration/login are displayed below the button, which can sometimes be missed by the user. Also, the error message is not specific. We could also have a toast message for success message for few seconds before moving to a different page.

**Suggested Solution**
I propose using toast notifications or popups to display error and success messages. These should:

- Be visually prominent and easily noticeable.
- Automatically disappear after a short duration (e.g., 3–5 seconds) but allow manual dismissal for user convenience.
- Be consistent with the application's design language and style.

**Alternative**
- Improving the visibility of inline messages (e.g., better styling).
- Using modal dialogs for all messages (but this could interrupt user workflows).

**Additional context**
If this change is agreed upon, I’d be happy to help implement it. @vinsdragonis  Let me know your thoughts!

**Comment by vinsdragonis** [comment]
Hi @swati082001  👋

Could you please clarify which version you are referring to?
If you are talking about the hosted version, please note that the server application is currently not being actively maintained online. However, if you mean a locally run version, this issue has been reported several times but has not yet been resolved.

If you would like to help address this issue, you are welcome to contribute. Please include a screenshot of the work you have done to ensure that the pull request functions correctly and does not introduce any breaking changes.

Thank you!  
@vinsdragonis

**Comment by swati082001** [comment]
Hey @vinsdragonis, I am referring to the locally run version. Will start working on it. Thanks for assigning.
