### ISSUE TITLE
Below the Nav Bar exist buttons to either login or register

### ISSUE THREAD

**Issue by Omafovbe** [vinsdragonis/Project-Nexus#83]
**Describe the bug**
On login and register page both have duplicate actions for users to register/login. A link on the nav bar to register and login and another button bottom right of nav bar click to register or login depending on which page you visit.

**To Reproduce**
1. Go to https://projectnexus.netlify.app/login
2. Also go to https://projectnexus.netlify.app/register

**Expected behavior**
Apart from the nav bar containing the expected links there shouldn't be any other just as on the project

**Screenshots**
1. ![image](https://user-images.githubusercontent.com/19856671/184928488-b62f5021-d274-4523-9810-30aabada70b7.png)
2. ![image](https://user-images.githubusercontent.com/19856671/184929060-b5015dba-5666-4608-803a-21ee5debc760.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version:  104.0.5112.81

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10S
 - OS: Android 12
 - Browser: Chrome Stock Browser
 - Version 96

**Additional context**

**Comment by vinsdragonis** [comment]
Correct me if I'm wrong, but are you saying that we have 2 duplicate buttons for register on the login page and 2 for login on the register page and so you want to remove those duplicates?

**Comment by vinsdragonis** [comment]
If you are interested in helping out, go right ahead! @Omafovbe

**Comment by Omafovbe** [comment]
Thanks would work on it

**Comment by vinsdragonis** [comment]
Thanks for your contribution. While what you've worked on works locally, there seems to be an issue with netlify for now. So viewing the same changes online could take a while.
I'm looking into this right now. So please rest assured that your work will soon be visible on the deployed version.

**Comment by vinsdragonis** [comment]
Okay, seems to show up correctly for me. We can consider this issue resolved.

**Comment by Omafovbe** [comment]
Thanks for the update. I also would love to work on the nav bar so as to
make it responsive. Would you wish I go ahead with that also?

**Comment by vinsdragonis** [comment]
Sure, go right ahead
