### ISSUE TITLE
Title of the website disappear after drag

### ISSUE THREAD

**Issue by 31Sanskrati** [vinsdragonis/Project-Nexus#85]
**Issue:**
On the home page of the website, when you drag the heading "Project Nexus Blog".  It disappears.

**Correct behavior:**
The heading should not get disappeared after the dragging over it.

**Desktop details:**
 - OS - Windows
 - Browser  - Brave
 - Version - 21H2
<img width="944" alt="Screenshot 2022-08-17 174313" src="https://user-images.githubusercontent.com/78686887/185115995-493af916-6232-4541-b4dc-f02b8147c81b.png">

**Comment by vinsdragonis** [comment]
This is something I've noticed just recently, and yes that is unusual and shouldn't happen.

**Comment by vinsdragonis** [comment]
If you're interested, then you can take up this issue.

**Comment by vinsdragonis** [comment]
Thanks a lot for your time and contribution @31Sanskrati 😄
