### ISSUE TITLE
Load more button not visible in mobile view

### ISSUE THREAD

**Issue by vinsdragonis** [vinsdragonis/Project-Nexus#98]
In a recent update, we added a load more button to load more posts as and when required. However, this button isn't visible on the mobile view, which prevents users from viewing older posts.
It would be convenient if we had this working on mobile devices too.

**Comment by Srikanth4533** [comment]
Actually its visible but,when there is no posts to load it will disappears.

**Comment by Srikanth4533** [comment]
Actually its visible, but when there is no posts to load it will not be visible.

**Comment by Srikanth4533** [comment]
![mobile](https://user-images.githubusercontent.com/92268136/185747151-88c5e4d0-61f7-4e14-bbf4-feb4664aaa10.png)
